sudo: require
language: node_js
services:
  - docker

before_install:
  - docker build -t emperor/docker-react -f Dockerfile.dev .

script: 
 - docker run emperor/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: docker-react
  environment: Dockerreact-env
  bucket_name: elasticbeanstalk-eu-north-1-840023474946
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRETE_KEY"